### ISSUE TITLE
[leancode_lint] custom_lint not detecting issues

### ISSUE THREAD

**Issue by SAGARSURI** [leancodepl/flutter_corelibrary#285]
Hey team,

Thank you for this great package. I really like your `custom_lint` rules. But I am not able to make it run in my multi-package flutter project setup. I have the following structure of my project:
```
my_movies/
 - app/
    - movie_app/
 - utilities/
    - movie_lint/
```
`movie_app`: my flutter app
`movie_lint`: my custom lint which internally use leancode_lint package

In my `movie_lint` package. I have `analysis_options.yaml` inside the `lib/` folder which have the following code:

```
include: package:leancode_lint/analysis_options.yaml

custom_lint:
  rules:
#    TODO: Add lint for design system [make task also]
    - use_design_system_item:
      AppText:
        - instead_of: Text
          from_package: flutter

analyzer:
  plugins:
    # Required for our custom lints support
    - custom_lint
  exclude:
    - '**/*.g.dart'
```

In my `movie_app` the `analysis_options.yaml` looks like this:
```
include: package:movie_lint/analysis_options.yaml
```

Now when I use this package inside my `movie_app` flutter app. The `dart analyze .` is working fine but `dart run custom_lint` is not detecting the issues in my codebase.
