### ISSUE TITLE
Using leancode linter above package:lint ?

### ISSUE THREAD

**Issue by EArminjon** [leancodepl/flutter_corelibrary#297]
Is it possible to use the leancode linter above actual package lint ? https://pub.dev/packages/lint

And so opt in only some specific new linter rule ?

**Comment by shilangyu** [comment]
If you want to use the custom lints and not the configuration of lints, then it is most certainly possible. You can not use it in the `include:` directive of `analysis_options` but follow the rest of the instructions in the readme.

Then to opt in to custom lints, you have to first disable all lints, and enable specifically those that you care about. For example:

```yaml
custom_lint:
  enable_all_lint_rules: false
  rules:
    - prefix_widgets_returning_slivers
```


Let me know if that helps and if you have more questions.
