### ISSUE TITLE
"use_design_system_item" lint should ignore import "hide" instructions

### ISSUE THREAD

**Issue by KamilSztandur** [leancodepl/flutter_corelibrary#342]
**What's wrong:**
Leancode Lints throw a warning when you hide a class that has corresponding name to the banned class in one of `use_design_system_item` lints.

**The unexpected result:**
<img width="878" alt="image" src="https://github.com/user-attachments/assets/15a8e62f-0613-4fa0-9f32-3f8e2184f87d">

**The expected result:**
I can hide this member without triggering the warning.

**How to reproduce:**
1. Setup `leancode_lints` for your project.
2. Add this to your `analysis_options.yaml`:
```yaml
custom_lint:
  rules:
    - use_design_system_item:
      AppBadge:
        - instead_of: Badge
          from_package: flutter
 ```
 3. Try to hide Badge class from material import:
 ```dart
 import 'package:flutter/material.dart' hide Badge;
 ```
