### ISSUE TITLE
Bump custom_lint_builder to ˆ0.7.0

### ISSUE THREAD

**Issue by Alvish0407** [leancodepl/flutter_corelibrary#388]
```yaml
dev_dependencies:
  custom_lint: ^0.7.0
  leancode_lint: ^14.2.0
  riverpod_lint: ^2.6.3
```
```shell
Resolving dependencies...
Because riverpod_lint >=2.6.2 <3.0.0-dev.0 depends on custom_lint_builder ^0.7.0 and leancode_lint 14.2.0 depends on custom_lint_builder ^0.6.4, riverpod_lint >=2.6.2 <3.0.0-dev.0 is incompatible with leancode_lint 14.2.0.
And because no versions of leancode_lint match >14.2.0 <15.0.0, riverpod_lint >=2.6.2 <3.0.0-dev.0 is incompatible with leancode_lint ^14.2.0.
So, because ... depends on both leancode_lint ^14.2.0 and riverpod_lint ^2.6.3, version solving failed.
```
