### ISSUE TITLE
Use analyzer rules only 

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#63]
## Practical explanation

This screenshot shows 2 warnings.
![Screenshot 2022-05-18 at 4 05 15 PM](https://user-images.githubusercontent.com/40357511/169060723-a7852bc1-88ae-4a4d-96e7-1c4a17b6849e.png)

### diagnostics
Clicking on `unused_element` redirects us to [dart.dev/tools](https://dart.dev/tools/diagnostic-messages#unused_field), to a section about a particular _diagnostic_ (aka _diagnostic message_ – in our case the _diagnostic_ is `unused_element`). This website doesn't use the "lint" word anywhere.

Diagnostics are specified in `analysis_options.yaml` like this:

```yaml
analyzer:
  errors:
    unused_element: false
    unused_field: true
```

[Learn more about diagnostic messages on dart.dev](https://dart.dev/tools/diagnostic-messages)

### lints
Clicking on `use_build_context_synchronously` redirects us to [dart-lang.github.io/linter](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html), to a page about a particular _lint rule_ (aka _lint_).

Lints are specified in `analysis_options.yaml` like this:

```yaml
linter:
  rules:
    use_build_context_synchronously: false
    library_private_types_in_public_api: true
```

[Learn more about linter rules on dart.dev](https://dart.dev/tools/linter-rules)

## output

I've talked with @RobertOdrowazLNCD about this today. We agreed that the distinction between _diagnostics_ and _lints_ is blurry.

~~He suggested that if possible, we should define both _diagnostics_ and _lints_ in `analyzer`, so there'll be a smaller chance of making a mistake and defining a _diagnostic_ in `linter.rules`).~~ i tried and looks like it's not possible (?)

PS I've found explanation of difference between _diagnostics_ and _lints_ [here](https://dart.dev/guides/language/analysis-options#the-analysis-options-file)
