### ISSUE TITLE
Update `leancode_lint` to use new `language` modes and remove `strong-mode`

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#96]
When using `leancode_lint` on Flutter beta, it spits out:

<img width="1035" alt="Screenshot 2023-03-16 at 11 35 38 PM" src="https://user-images.githubusercontent.com/40357511/225768115-a0b0357b-b1d4-488f-b474-fe71e8aff9f0.png">

another example:

<img width="1035" alt="Screenshot 2023-03-16 at 11 39 02 PM" src="https://user-images.githubusercontent.com/40357511/225768571-9c54e3ab-9f3d-4464-b9b0-9c3169c15bd3.png">

The cause lies [here](https://github.com/leancodepl/flutter_corelibrary/blob/5f8e110c50b76b413663418dcf7f4a3a2ed63649/packages/leancode_lint/lib/analysis_options.yaml#L3-L6):

```yaml
analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```

We should change it to:

```yaml
analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
```

as suggested by [Customizing static analysis](https://dart.dev/guides/language/analysis-options) docs.

Learn more:
- https://dart.dev/guides/language/analysis-options#enabling-additional-type-checks
- https://github.com/dart-lang/sdk/issues/50680
- https://github.com/dart-lang/sdk/issues/50679

cc: @Albert221 @shilangyu
